nodeLinker: node-modules

npmRegistries:
  //git.xpegma.eu/api/v4/projects/196/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: kPGmJxvETN8hLA1i48B_

npmScopes:
  pg-ui:
    npmRegistryServer: "https://git.xpegma.eu/api/v4/projects/196/packages/npm/"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
